spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/local
spring.datasource.username=developer
spring.datasource.password=developer

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
